final List<Map<String, dynamic>> articles = [
  {
    'id':1,
    'author_img': 'https://c.tadst.com/gfx/750x500/authors-day-fun.jpg',
    'banner':
    'https://news.sanfordhealth.org/wp-content/uploads/2017/12/455237505-780x537.jpg',
    'title': 'What is a Cardiology?',
    'author': 'Aleyna Eser',
    'description':'Cardiology is the study and treatment of disorders of the heart and the blood vessels.',
    'article': 'Cardiology is the study and treatment of disorders of the heart and the blood vessels. A person with heart disease or cardiovascular disease may be referred to a cardiologist.',
    'date': 'Sep 23,2021 at 20:11',
    'cat': 'Cardiology',
    'comments':'2',
    'likes':'20',
    'isLiked':true,
    'isMarked':false,
  },
  {
    'id':2,
    'author_img': 'https://c.tadst.com/gfx/750x500/authors-day-fun.jpg',
    'banner':
    'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/06/dermatologist-skin-doctor-1296x728-header.jpg?w=1155&h=1528',
    'title': 'What is a Dermatology?',
    'author': 'Aleyna Eser',
    'description':'Cardiology is the study and treatment of disorders of the heart and the blood vessels.',
    'article': 'Dermatology is the branch of medicine dealing with the skin. It is a speciality with both medical and surgical aspects.',
    'date': 'Sep 23,2021 at 20:13',
    'cat': 'Dermatology',
    'likes':'250',
    'comments':'2',
    'isLiked':false,
    'isMarked':false
  },
  {
    'id':3,
    'author_img': 'https://c.tadst.com/gfx/750x500/authors-day-fun.jpg',
    'banner': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqK-dXOiNpHkibNVWmAbn0Ym6b5Me80o0bEg&usqp=CAU',
    'title': 'What is a Neurologist?',
    'author': 'Aleyna Eser',
    'description':'Cardiology is the study and treatment of disorders of the heart and the blood vessels.',
    'article': 'A neurologist is a physician specializing in neurology and trained to investigate, or diagnose and treat neurological disorders.',
    'date': 'Sep 23,2021 at 20:10',
    'cat': 'Neurology',
    'likes':'205',
    'comments':'20',
    'isLiked':true,
    'isMarked':true,
  },
  {
    'id':4,
    'author_img': 'https://c.tadst.com/gfx/750x500/authors-day-fun.jpg',
    'banner': 'https://leverageedublog.s3.ap-south-1.amazonaws.com/blog/wp-content/uploads/2020/03/11193424/Difference-Between-Psychologist-and-Psychiatrist.jpg',
    'title': 'What is a Psychiatrist?',
    'author': 'Aleyna Eser',
    'description':'Cardiology is the study and treatment of disorders of the heart and the blood vessels.',
    'article': ' A medical doctor specializing in psychiatry psychiatrist someone with a medical degree (MD) who specializes in mental illness A Psychiatrist can prescribe drugs for patients, and psychologist cannot child psychiatry Branch of medicine concerned with mental, emotional, and behavioral disorders of childhood.',
    'date': 'Sep 23,2021 at 20:12',
    'cat': 'Psychiatrist',
    'likes':'10',
    'comments':'20',
    'isLiked':true,
    'isMarked':true
  },
  {
    'id':4,
    'author_img': 'https://c.tadst.com/gfx/750x500/authors-day-fun.jpg',
    'banner': 'https://leverageedublog.s3.ap-south-1.amazonaws.com/blog/wp-content/uploads/2020/03/11193424/Difference-Between-Psychologist-and-Psychiatrist.jpg',
    'title': 'What is a Psychiatrist?',
    'author': 'Aleyna Eser',
    'description':'Cardiology is the study and treatment of disorders of the heart and the blood vessels.',
    'article': ' A medical doctor specializing in psychiatry psychiatrist someone with a medical degree (MD) who specializes in mental illness A Psychiatrist can prescribe drugs for patients, and psychologist cannot child psychiatry Branch of medicine concerned with mental, emotional, and behavioral disorders of childhood.',
    'date': 'Sep 23,2021 at 20:12',
    'cat': 'Psychiatrist',
    'likes':'10',
    'comments':'20',
    'isLiked':true,
    'isMarked':true
  },
];